### PR TITLE
Add bodeul

### PR DESCRIPTION
**Pull request by jeanlucmargot**
I am proposing to add the capability to call the routine bodeul.  I created a new test and tested it successfully.  Thank you.

### CODE REVIEW

**Comment by jessemapel** [comment]
Last time functions like this (documented in Fortran SPICE but not C SPICE) were added, they also had to be added to the library file for the windows cspice repo. You may want to put in a PR over there similar to this one:

https://github.com/conda-forge/cspice-feedstock/commit/bcb8cf4b10e6a90651998a1ba7ec761147d9b111

I don't see bodeul_ defined there yet.

**Comment by jeanlucmargot** [comment]
> Last time functions like this (documented in Fortran SPICE but not C SPICE) were added, they also had to be added to the library file for the windows cspice repo. You may want to put in a PR over there similar to this one:
> 
> [conda-forge/cspice-feedstock@bcb8cf4](https://github.com/conda-forge/cspice-feedstock/commit/bcb8cf4b10e6a90651998a1ba7ec761147d9b111)
> 
> I don't see bodeul_ defined there yet.

Thank you. 
Perhaps I am misunderstanding something.  I defined bodeul_ on line 13 of appveyor/cspide.def.  Is something else required?

**Comment by jessemapel** [comment]
@jeanlucmargot The appveyor CI uses the get_spice script to get CSPICE which then uses the def file you modified. The conda-forge feedstock is a different way to get CSPICE that is used when spiceypy is installed from anaconda & conda-forge. The repo & PR that I linked to is what creates the CSPICE package for anaconda & conda-forge. Unfortunately, there are duplicate def files because of the different ways that users can get CSPICE.

**Comment by jeanlucmargot** [comment]
> @jeanlucmargot The appveyor CI uses the get_spice script to get CSPICE which then uses the def file you modified. The conda-forge feedstock is a different way to get CSPICE that is used when spiceypy is installed from anaconda & conda-forge. The repo & PR that I linked to is what creates the CSPICE package for anaconda & conda-forge. Unfortunately, there are duplicate def files because of the different ways that users can get CSPICE.

Thank you @jessemapel for educating me.  I submitted the PR as requested.

**Comment by AndrewAnnex** [comment]
@jeanlucmargot thanks for the contribution(s)! I think it looks good to me and thanks for following existing code style closely. I'll merge later tonight  tonight once all tests pass (current failure isn't important, ci build just needs to be redone)

**Pull request merged**
